### ISSUE TITLE
看这里，说说你对GitHub的疑惑和期待

### ISSUE THREAD

**Issue by young24** [Wenlab/Computation-Neuro-Course#2]
欢迎来到这门全新的，也是充满挑战的课程。GitHub将作为第二课堂来实现关于课程内容、作业、答疑的工具；同时GitHub也是一个以Git版本管理技术为内核的项目管理网站，可以有效地管理你的代码、个人网站甚至是科研课题。
之后，温老师也许会布置一个大作业，让大家利用GitHub以一种高效的团队协助的方式来完成这个题目。

**大家有任何关于GitHub的问题、疑惑及期待都可以写在这里。我们都会一一解答的。**

大家可以从下面这些GitHub的入门教程开始，亲自通过实践的方式去了解和使用GitHub；之后我们应该会安排一次简短的关于GitHub的介绍，但更为重要的是请大家花一些时间去实践并且体会GitHub的优势和威力。

- [Hello World](https://guides.github.com/activities/hello-world/)
- [详细的利用GitHub搭建个人网站的说明](https://www.jianshu.com/p/d344d51bcc4e)
- [探索GitHub](https://guides.github.com/)

**Comment by Physics-Lee** [comment]
Nice Instruction!
