### ISSUE TITLE
Reconstruct the neuronal connectivity in zebrafish brain

### ISSUE THREAD

**Issue by wenquan** [Wenlab/Computation-Neuro-Course#36]
Dear all,

I am looking for highly motivated students with strong quantitative background to analyze axon and dendritic morphology and to estimate potential connectivity between different cell types in larval zebrafish brain. This exciting project is in collaboration with Professor Jiulin Du at Institute of Neuroscience in Shanghai. We are working on an unprecedented dataset (~5000 reconstructed neurons using confocal microscopy and more to come). Please let me know if you are interested!

**Comment by HoutonBosta** [comment]
请问Problem Set 2第一大题的第二问所给提示中是否存在问题？
![image](https://github.com/Wenlab/Computation-Neuro-Course/assets/36225651/c3922bf2-d2c4-4b8e-bf07-6ede86bef597)
其中指数上的分子nT这项前面要加一个负号
这是我的证明
![IMG_20231010_145625](https://github.com/Wenlab/Computation-Neuro-Course/assets/36225651/2aca19c0-6ca4-432e-8a90-aaa9b59b3e07)
@wenquan 
胡博洲 JL22020008
