### ISSUE TITLE
鼓励大家提issue！

### ISSUE THREAD

**Issue by Physics-Lee** [Wenlab/Computation-Neuro-Course#46]
* 鼓励大家在GitHub上提issue，提出有价值问题的直接在**总评**里加1-2分！回答问题回答得非常好的也直接在**总评**里加1-2分！（每人限一次）
* 老师、助教看到issue也会回答的。
* 我们有可能会在issue里发布一些招聘广告，比如[此处](https://github.com/Wenlab/Computation-Neuro-Course/issues/36)
* 本课的小目标之一是让大家熟悉Git和GitHub，在现在这个时代，你不熟悉GitHub、不会提issue，会损失很多有价值的信息。

**Comment by Pripribiologist** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我是李品洁，已收到您发来的邮件，我会尽快处理，祝好~
