### ISSUE TITLE
有关Reichardt Model的模拟

### ISSUE THREAD

**Issue by Physics-Lee** [Wenlab/Computation-Neuro-Course#47]
[我提供的模拟代码](https://github.com/Wenlab/Computation-Neuro-Course/tree/Fall2023/Just%20For%20Fun/Reichardt%20Model)。

以下问题，我希望你们去探索。可以自己探索，也可以搜查资料。

* **如何模拟出从右往左的效果？**
* 为什么会出现“上半部分从左往右，下半部分从右往左”的效果？
  * 你能提出一个比Reichardt Model更好的Model来解释这个现象吗？
* 运动和点的分布是否有关？
  * 可以尝试均匀分布、高斯分布
  
**模拟出从右往左的效果**是最重要的。

**Comment by WENYUEHu03** [comment]
我用我的电脑跑了一下助教的代码，可能因为我的电脑比较卡，我观察到的效果是点既可以往左运动又可以往右运动，且往右运动的速度比往左运动的速度慢。所以我猜测仍然可以用Reichardt Model解释这个现象，即\tau在不同的观察下是可以变化的。观察到从右往左时，\tau的数值是从左往右的两倍，这时候会出现黑点和黑点同时出现在M处，即出现从左往右的现象。

https://github.com/Wenlab/Computation-Neuro-Course/assets/141335810/d6bcdf96-b422-4ad0-9bfd-f905edfc998c

**Comment by Physics-Lee** [comment]
"\tau在不同的观察下是可以变化的"指什么？

**Comment by WENYUEHu03** [comment]
就是人以不同方式观察时，\tau可能是不同的。（我不是很确定这个观点，但我多次看result.mp4似乎可以看出不同的结果…？）

**Comment by JinHui2022** [comment]
我在模拟Reichardt Model时也遇到了那位同学发现的问题，就是对于同一个模拟结果，有的时候能够观察到点往左移动，有的时候能够观察到点往右移动。譬如，对于助教发的那个演示视频，我的初感觉确实是上半部分在往右移动，下半部分在往左移动，但是当我注意看下半部分时，就会发现下半部分给我的感觉又是在往右移动了。
因此，我的看法与楼上的看法是相似的，并且认为注意力可能对于模型中的延迟时间τ是有影响的。而且我怀疑视网膜上不同位置的感光的神经元的延迟时间有些微的不同，因为一般我们在使用电脑时，屏幕所占据的视角还是比较可观的，这导致了上半部分和下半部分的影像投射到视网膜不同的区域上了，由于不同的区域在延迟时间上有一定的差异，于是造成了观感的不同。我试过距离稍远观察我的电脑屏幕上播放的演示视频，这时上下部分给我的观感就比较一致了。当然，这很主观，不同人可能感受还是有所不同。
最后，我觉得需要注意的是，人脑的运动感知并不只是在一维尺度上工作，在这个模拟工作中是应该考虑二维尺度上的效果的。我想这就解释了为什么助教的搭档会发现点在上下跳动，因为从纵向上看，点也是在换颜色的，但是由于初始的点分布pattern不一样，所以不同纵轴上的\omega是有所不同的，因而有的给出向上运动的感觉，有的给出向下运动的感觉。考虑到这一点，我觉得又可以回到刚才的问题，就是为什么上半部分和下半部分有所不同，假使我们认为有八个unit在感受运动方向，分别对应上下左右和左上、左下、右上、右下这八个方位，最后的总体观感是这八个神经元的响应的矢量叠加，那么纵方向上的刺激就可能对横方向上的判断产生干扰。比如本来右侧刺激强于左侧刺激，但是左上的刺激要强于右下的刺激，而且左上的刺激在横方向的分量也要强于右侧刺激，这就会导致观者在被给出判断点在左移还是右移这个任务时，会认为点在左移

**Comment by Physics-Lee** [comment]
很好的想法

**Comment by Physics-Lee** [comment]
> 我用我的电脑跑了一下助教的代码，可能因为我的电脑比较卡，我观察到的效果是点既可以往左运动又可以往右运动，且往右运动的速度比往左运动的速度慢。所以我猜测仍然可以用Reichardt Model解释这个现象，即\tau在不同的观察下是可以变化的。观察到从右往左时，\tau的数值是从左往右的两倍，这时候会出现黑点和黑点同时出现在M处，即出现从左往右的现象。
> 
>  a0607aeb3b6d58cb68f768b41cd29b22.mp4

你可尝试一下不要固定x、y的坐标（用我之前历史版本的代码），看看会如何。

**Comment by Physics-Lee** [comment]
> 我在模拟Reichardt Model时也遇到了那位同学发现的问题，就是对于同一个模拟结果，有的时候能够观察到点往左移动，有的时候能够观察到点往右移动。譬如，对于助教发的那个演示视频，我的初感觉确实是上半部分在往右移动，下半部分在往左移动，但是当我注意看下半部分时，就会发现下半部分给我的感觉又是在往右移动了。 因此，我的看法与楼上的看法是相似的，并且认为注意力可能对于模型中的延迟时间τ是有影响的。而且我怀疑视网膜上不同位置的感光的神经元的延迟时间有些微的不同，因为一般我们在使用电脑时，屏幕所占据的视角还是比较可观的，这导致了上半部分和下半部分的影像投射到视网膜不同的区域上了，由于不同的区域在延迟时间上有一定的差异，于是造成了观感的不同。我试过距离稍远观察我的电脑屏幕上播放的演示视频，这时上下部分给我的观感就比较一致了。当然，这很主观，不同人可能感受还是有所不同。 最后，我觉得需要注意的是，人脑的运动感知并不只是在一维尺度上工作，在这个模拟工作中是应该考虑二维尺度上的效果的。我想这就解释了为什么助教的搭档会发现点在上下跳动，因为从纵向上看，点也是在换颜色的，但是由于初始的点分布pattern不一样，所以不同纵轴上的\omega是有所不同的，因而有的给出向上运动的感觉，有的给出向下运动的感觉。考虑到这一点，我觉得又可以回到刚才的问题，就是为什么上半部分和下半部分有所不同，假使我们认为有八个unit在感受运动方向，分别对应上下左右和左上、左下、右上、右下这八个方位，最后的总体观感是这八个神经元的响应的矢量叠加，那么纵方向上的刺激就可能对横方向上的判断产生干扰。比如本来右侧刺激强于左侧刺激，但是左上的刺激要强于右下的刺激，而且左上的刺激在横方向的分量也要强于右侧刺激，这就会导致观者在被给出判断点在左移还是右移这个任务时，会认为点在左移

你可否设计一个实验或模拟来说明在看电脑屏幕的此类模拟时必须考虑2D而不仅仅是1D？比如说，在你这个模拟中，有2个unit的生物和有8个unit的生物会有非常不一样的视觉感知？

**Comment by YkLn0419** [comment]
我觉得上面两个同学说的比较全面，注意力可能会改变τ的大小进而影响D(x)再进而影响R(x)，但就我个人在模拟数据时的感受而言，注意力可能不是唯一因素。
我在模拟实验时将自己和电脑屏幕之间的距离固定，也就是将视野大小固定再开始观察，在pause(τ)值达到较小值时可以观察到一行points的两种运动状态，而此时我的注意力是一定的（因为我视线集中在某一条上，但仍有误差），τ值理论上没有变化，影响观察结果的唯一因素是因为我在观察时不断暗示自己“这一行点在朝XX方向运动”导致了结果的不同。
因此，基于自身感受，我认为视觉信号的处理过程可能还受到大脑的上对下调控，大脑会基于观察结果R(x)进一步进行处理，而不是直接输出R(x)，可能还存在某种调控函数h(x)，最后的输出结果为R'(x)=(R*h)(x)，h(x)函数表达式可能与神经网络结构有关（因为这个视频的观察结果在我看来比较主观）。

**Comment by JinHui2022** [comment]
> > 我在模拟Reichardt Model时也遇到了那位同学发现的问题，就是对于同一个模拟结果，有的时候能够观察到点往左移动，有的时候能够观察到点往右移动。譬如，对于助教发的那个演示视频，我的初感觉确实是上半部分在往右移动，下半部分在往左移动，但是当我注意看下半部分时，就会发现下半部分给我的感觉又是在往右移动了。 因此，我的看法与楼上的看法是相似的，并且认为注意力可能对于模型中的延迟时间τ是有影响的。而且我怀疑视网膜上不同位置的感光的神经元的延迟时间有些微的不同，因为一般我们在使用电脑时，屏幕所占据的视角还是比较可观的，这导致了上半部分和下半部分的影像投射到视网膜不同的区域上了，由于不同的区域在延迟时间上有一定的差异，于是造成了观感的不同。我试过距离稍远观察我的电脑屏幕上播放的演示视频，这时上下部分给我的观感就比较一致了。当然，这很主观，不同人可能感受还是有所不同。 最后，我觉得需要注意的是，人脑的运动感知并不只是在一维尺度上工作，在这个模拟工作中是应该考虑二维尺度上的效果的。我想这就解释了为什么助教的搭档会发现点在上下跳动，因为从纵向上看，点也是在换颜色的，但是由于初始的点分布pattern不一样，所以不同纵轴上的\omega是有所不同的，因而有的给出向上运动的感觉，有的给出向下运动的感觉。考虑到这一点，我觉得又可以回到刚才的问题，就是为什么上半部分和下半部分有所不同，假使我们认为有八个unit在感受运动方向，分别对应上下左右和左上、左下、右上、右下这八个方位，最后的总体观感是这八个神经元的响应的矢量叠加，那么纵方向上的刺激就可能对横方向上的判断产生干扰。比如本来右侧刺激强于左侧刺激，但是左上的刺激要强于右下的刺激，而且左上的刺激在横方向的分量也要强于右侧刺激，这就会导致观者在被给出判断点在左移还是右移这个任务时，会认为点在左移
> 
> 你可否设计一个实验或模拟来说明在看电脑屏幕的此类模拟时必须考虑2D而不仅仅是1D？比如说，在你这个模拟中，有2个unit的生物和有8个unit的生物会有非常不一样的视觉感知？

抱歉，最近较忙，而且一直想着把相关实验设计付诸实践了之后再来进行交流。我的实验设计大概是对照组初始pattern是图1所示，实验组初始pattern是图2所示，然后让奇数行进行换色。这样对照组由于没有在纵方向上的干扰，按照理论给人的视觉应该是黑点在向左或是向右运动，而实验组由于具有纵方向上的干扰，这里的干扰由于pattern是有规律的，所以不同于最初的模型，因而给人在纵方向上的速度判断是恒定的，最终给人的视觉效果应该是斜方向上的。此外也应该能够观察到当我扩大颜色交替行之间的距离时，也就相当于减小了纵方向刺激的\omega，给人的视觉效果也会发生变化。同时需要注意给被试的任务应该改为，黑点的运动方向是什么？而不再是黑点的运动是向左还是向右？最近才有空开始将这个实验设计付诸实践，但是初期效果不是很理想，或许需要探索最合适的颜色交替行之间的距离。
此外，我发现issue里面的模型或许存在一定问题，就是按照温老师课程介绍的，在这个模型中应该模拟出一种通过改变点的颜色来实现点在发生移动这种错觉，但是issue里面的代码实际上不仅改变了颜色，同时也更改了点的位置，这可能对于模拟有一定影响。
最后，可能需要说明的是，有关2D必须考虑这个因素，我是因为课上听到温老师说这是目前对于运动感知的解释才会提出的，查阅文献也发现这样的建模，其中就有用8个unit来进行模拟的建模工作。但是我不清楚是否就会有只有2个unit的生物和只有8个unit的生物，所以我不能想出怎样了解这样生物的视觉感知的方法，换句话说，即使我设计了一个实验，我也无法确认是否2个unit的生物和8个unit的生物会有不一样的感知，因为它们可能就不存在，我的结论得不到证明

**Comment by JinHui2022** [comment]
![IMG_20230912_211925](https://github.com/Wenlab/Computation-Neuro-Course/assets/106484837/f32408b8-b3e2-4bc2-85a8-9ca89222afdf)

**Comment by Physics-Lee** [comment]
@JinHui2022 

> 此外，我发现issue里面的模型或许存在一定问题，就是按照温老师课程介绍的，在这个模型中应该模拟出一种通过改变点的颜色来实现点在发生移动这种错觉

这个模型的意思是在移动的同时改变颜色。

> 初期效果不是很理想，或许需要探索最合适的颜色交替行之间的距离。

模拟时记得要把背景颜色设为灰色，这很重要。

> 我不清楚是否就会有只有2个unit的生物和只有8个unit的生物

我的意思并不是真的要去寻找只有2个unit的生物和只有8个unit的生物，而是设计一个更好的模拟证明，人在看这种视频时，必须要考虑2D，而不仅仅是考虑1D。你设计的这个实验看起来很有希望成功。

**Comment by Physics-Lee** [comment]
@YkLn0419 

在我提供的这个尚未成功的模拟里，主观的确会有一定影响。

但是在温老师上课放的两个视频里，对于第二个视频，我们都出现了很明显的错觉，这就是主观改变不了的了。

**Comment by Physics-Lee** [comment]
一些有用的链接：
* [Phi_phenomenon](https://en.wikipedia.org/wiki/Phi_phenomenon) 
* [温老师上课用的gif](https://clarklab.yale.edu/movies)

**Comment by Physics-Lee** [comment]
我在这次[commit](https://github.com/Wenlab/Computation-Neuro-Course/commit/6317043823b63aca45a5a9155a7e4e2005b2cc3e)中加入了消失再出现的算法，这是[原图出处](https://clarklab.yale.edu/movies)所写的模拟方法，但是所得效果还不如我第一次做出的result.mp4

**Comment by Pripribiologist** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我是李品洁，已收到您发来的邮件，我会尽快处理，祝好~
