### ISSUE TITLE
关于作业第三题的问题

### ISSUE THREAD

**Issue by peterlv2003** [Wenlab/Computation-Neuro-Course#50]
作业第三题中提到“given a connectivity rule......that minimize the total wires”，请问这里的connectivity和wire是什么关系呢？是不同的connectivity对应连接的权重不同吗？然后总长度按照距离加权求和计算？

**Comment by Physics-Lee** [comment]
- connectivity 指某一个神经元要按照某种方式和其它神经元相互连接。某种方式在第一问里是均匀分布，在第二问里是半椭圆分布。
- total wire 指连接的总长度。

**Comment by Physics-Lee** [comment]
想象神经元是二维的点阵

**Comment by peterlv2003** [comment]
我知道它是一种分布，但是这种分布与连接的总长度有什么关系呢？如果是均匀分布，是不是连接不同delta的神经元的权重相同；如果是第二种分布，就是每个delta对应的权重不同。是这样吗？

**Comment by Physics-Lee** [comment]
总长度就是二维的点阵之间连接的线的总长度。

**Comment by peterlv2003** [comment]
是的，但是如果总是连接所有的点，总长度就是定值。我想知道的是，分布不同是不是意味着有一些连接要去掉？只对一定比例的神经元建立连接？

**Comment by Physics-Lee** [comment]
是Sent from my phone-------- Original message --------From: peterlv2003 ***@***.***>Date: Wed, Sep 27, 2023, 16:37To: Wenlab/Computation-Neuro-Course ***@***.***>Cc: Yixuan Li ***@***.***>, Assign ***@***.***>Subject: Re: [Wenlab/Computation-Neuro-Course] 关于作业第三题的问题 (Issue #50)
是的，但是如果总是连接所有的点，总长度就是定值。我想知道的是，分布不同是不是意味着有一些连接要去掉？只对一定比例的神经元建立连接？

**Comment by peterlv2003** [comment]
好的，谢谢！
