### ISSUE TITLE
Problem Set II 1b Hint叙述

### ISSUE THREAD

**Issue by WENYUEHu03** [Wenlab/Computation-Neuro-Course#52]
$I_a(t)=-J_a\sum_0^{\infty} e^{-\frac{nT+t}{\tau_a}}$ for $t \in [nT, (n+1)T]$，这个求和号是对谁求和？对n吗？但是n不是一个给定的数吗？（for $t \in [nT, (n+1)T]$）

**Comment by Yue9Shang** [comment]
Just a glance, 我感觉可能是对n求和，然后后面的这个范围的n是个typo，本意可能是告诉我们Ia是关于t是周期函数

**Comment by wenquan** [comment]
That's right.  It should be $I_a(t)=-J_a\sum_{n=0} ^{\infty} e^{-\frac{nT+t}{\tau_a}}$ for $t \in [0, T)$. Thanks for pointing this out.
