### ISSUE TITLE
一个幽灵般的问题

### ISSUE THREAD

**Issue by Physics-Lee** [Wenlab/Computation-Neuro-Course#53]
<img width="485" alt="1" src="https://github.com/Wenlab/Computation-Neuro-Course/assets/68525696/217b6b2a-ae6f-4c3e-af57-7559268ec2fc">
<img width="478" alt="2" src="https://github.com/Wenlab/Computation-Neuro-Course/assets/68525696/15b26016-3651-4a6b-a6e8-c11d7921c311">

**Comment by WENYUEHu03** [comment]
数学家首先考虑如何写出这个问题的样本空间？

**Comment by Physics-Lee** [comment]
可以啊，写呗。

**Comment by Yue9Shang** [comment]
我感觉这个对于这个数学问题，结果应该是1的。但考虑到神经元是有一定大小的，用这个数学模型并不合适，可能需要加上限制，红色点的区域应至少有一个长度。如果再假设该系统空间平移对称，温老师的模型是很有道理的。

**Comment by Physics-Lee** [comment]
@Yue9Shang

物理上，温老师的做法似乎是唯一一种可行的做法。

数学上，这个问题的答案很反直觉——把一条有限长的线段上任意有限长度染色，它上面任何其它有限长线段含有红色的点的概率竟然都是1。

**Comment by forrestjhliu** [comment]
According to measure theory, in Lebesgue measure, $\mu (\mathbb Q)= 0$, but every interval on [0,1] 's intersection with $\mathbb Q$ is not empty. So this is related to what is “线段” in the question. In math, you can easily fill up [0,1] by $\mathbb Q$ with zero measure, but in the real-world everything must have a "measure" >0.

**Comment by Physics-Lee** [comment]
Yeah, that is right, if you make $\mathbb Q$ to be red, then every interval with finite measure on [0,1] contains red points.

I am asking another **math** question: if you turn a finite interval (set it as $a$) of [0,1] to be red, the interval can be splitted infinitely, then what is the probability of another finite interval containing red points?

It seems that, no matter how small $a$ is, as long as $a > 0$, then $P = 1$
