### ISSUE TITLE
Raman Cajal vs Francis Crick

### ISSUE THREAD

**Issue by Physics-Lee** [Wenlab/Computation-Neuro-Course#54]
Raman Cajal once wrote

> We realized that all of the various conformations of the neuron and its various components are simply morphological adaptations governed by laws of conservation for time, space, and material.

However, Francis Crick wrote

> Arguments about “efficiency” are thus almost always to be mistrusted in biology since we don’t know the exact problems faced by myriads of organisms in evolution. And without knowing that, how can we decide what form of efficiency paid off?

Who do you agree with?

**Comment by Physics-Lee** [comment]
Francis Crick's Explanation: 
> The genetic code is a very good example of what I mean. Who could
possibly invent such a complex allocation of the sixty-four triplets (see
appendix B)? Surely the comma-free code (page 99) was all that a theory
should be. An elegant solution based on very simple assumptions—yet
completely wrong. Even so, there is a simplicity of a sort in the genetic
code. The codons all have just three bases. The Morse code, by contrast, has
symbols of different lengths, the shorter ones coding the more frequent
letters. This allows the code to be more efficient, but such a property may
have been too difficult for nature to evolve at that early time.

These sentences are from _What Mad Pursuit_

**Comment by Physics-Lee** [comment]
I will upload my personal opinion 1 day later.

**Comment by Yue9Shang** [comment]
我更支持Francis的观点，即使是最简单的热力学系统，我们也不能仅仅根据能量最低确定态流动方向，我们也要考虑熵（thermal的效应），因此有了自由能等概念。更何况复杂如生命系统呢。

**Comment by Physics-Lee** [comment]
# My Personal Opinion

## Paul Dirac's quote

Paul Dirac once said

> My equation is so beautiful that it can not be wrong.

However, we all know that many beautiful models are wrong.



## 2 criterion

You can raise your model based on anything: efficiency, beauty, simplicity, imagination, or anything else you like. But you must **go back to experiments**, instead of keeping daydreaming and arguing.



There are 2 criterion to check if your model is a good/useful model.

* Explain the existing experiment phenomena well.
* Predict new experiment phenomena. **The more unexpected, the better.**



So, think about the models in the history of biology, which are good models and which are bad?



## Good

|                                         | Model                       | Unexpected Experiments Results Predicted                     |
| --------------------------------------- | --------------------------- | ------------------------------------------------------------ |
| Darwin                                  | Nature Selection            | You can force the pet to evolve different colors in very short period (30 years) |
| Mendel                                  | Mendel Laws                 | 9:3:3:1                                                      |
| Morgen, Bridges, Sturtevant, Muller [1] | Genes locate in chromosome  | Sex-linked-inheritance (伴性遗传); linked-inheritance (连锁遗传); Crossover (交叉互换); Drosophila Atlas (果蝇图谱)[2] |
| Salvador Luria, Max Delbruck            | Luria-Delbruck Distribution | see [Here](https://en.wikipedia.org/wiki/Luria%E2%80%93Delbr%C3%BCck_experiment) |
| Watson, Crick, Wilkins, Franklin        | DNA Double Helix            | semi conservative replication                                |
| Watson, Crick, George Gamow             | Triplet code                | exps of Nirenberg                                            |
| Alan Hodgkin, Andrew Huxley             | HH Model                    | You can do many things to a single neuron in vitro. [3]      |
| Many                                    | Cable Theory                | You can do many things to axons in vitro. [3]                |

[1] Morgen gave his Nobel Prize money to his group, including Bridges, Sturtevant and Muller.

[2] see CH3.3 of *Biological Physics* by Philip Nelson

[3] For example, use $K_2SO_4$ to replace cytoplasmic matrix.



## bad

* Comma-free code by Francis Crick.
* Theory of two currents in vision.



## Think about Physics

In physics, there are more cases. I list a little, leaving you to supplement them. You may get bonus points for it.

|                  | Model                                          | Unexpected Experiments Results Predicted |
| ---------------- | ---------------------------------------------- | ---------------------------------------- |
| Copernicus       | heliocentrism                                  | annual paralla (周年视差)                |
| Newton           | Newton 3 laws and Law of universal gravitation | Neptune                                  |
| Faraday, Maxwell | Use field to replace action at a distance      | electromagnetic wave                     |
| Einstein         | Special Relativity                             | $\mu$ in the cosmic ray                  |



## Summary

**All in all, efficiency, beauty, simplicity, imagination are all good ways to build a theoretical model, but, your model should not only explain current experiment results, but also predict new experiment phenomena.**
