### ISSUE TITLE
2022秋季学期第一次作业第三题

### ISSUE THREAD

**Issue by Physics-Lee** [Wenlab/Computation-Neuro-Course#55]
秀丽线虫是世界上第一个测出连接组的生物，科学家们分析了大量的电镜数据，终于在1986年得到了它的连接组。

它有302个神经元，5000个化学突触，600个电突触，2000个神经肌肉接头。

2022秋的第三题，我们被要求随机产生302个点和5000个边，然后比较线虫的连接组里相比随机网络多了哪些模式（生物学家称之为motif）。

结果如下：

![20231006-123013](https://github.com/Wenlab/Computation-Neuro-Course/assets/68525696/608c29c5-7f3b-4cb7-a7c4-bf148b0b8c01)

(Figure from Qiqi Xian)

我们发现有5个模式**多了很多**（用统计学家的话说，p-value < 0.01）

你认为这说明了什么？

**Comment by Physics-Lee** [comment]
提示（仅仅是我的个人看法，也可以不被这种思路束缚）：
1 这5个模式有什么共同点？
2 这个共同点说明了什么？

**Comment by Physics-Lee** [comment]
注：此结果已经经过多重假设检验矫正。

**Comment by Yue9Shang** [comment]
看不懂图...三角形是神经肌肉接头？线是突触？anyway，用助教的思路，共同点是至少有一个点有两个三角形，且三角形是完整的。因为是和随机网络相比，一个很直接的结论是，在这个共同点下的线虫的连接组具有较高的特异性

**Comment by Physics-Lee** [comment]
点是神经元，线是突触，三角形仅仅是代表方向。化学突触是单向的，因此，用数学家的话说，这是一个有向图。

**Comment by Physics-Lee** [comment]
<img width="914" alt="temp" src="https://github.com/Wenlab/Computation-Neuro-Course/assets/68525696/d3f808f5-cd5b-4baa-b1a0-d99a3507f6b3">


补充一下p-value
