### ISSUE TITLE
SNNs Startup Materials Requirement

### ISSUE THREAD

**Issue by forrestjhliu** [Wenlab/Computation-Neuro-Course#56]
I have learnt how a neuron works under the spiking model. However, I couldn't find some startup materials about the architecture and training progress of SNNs that were easy to comprehend. I was wondering if Prof. Wen@wenquan had some comprehensible and inspiring startup materials. Thank you very much!

**Comment by Physics-Lee** [comment]
Our lab has a forked [repo](https://github.com/Wenlab/SpikingNeuralNetworks.jl) about SNN. I haven't played it on my own yet and don't know if it is suitable for beginners. Hope Prof. Wen @wenquan  can give you some materials.

**Comment by wenquan** [comment]
I have been using this [Julia code](https://github.com/AStupidBear/SpikingNeuralNetworks.jl) for generating spiking neural network as well as other models for a while. It was written by my 路遥，a former physics student from USTC.  Here is a python package https://github.com/Shikhargupta/Spiking-Neural-Network
