### ISSUE TITLE
请问Problem Set 2第一大题的第二问所给提示中是否存在问题？

### ISSUE THREAD

**Issue by HoutonBosta** [Wenlab/Computation-Neuro-Course#57]
请问Problem Set 2第一大题的第二问所给提示中是否存在问题？
![image](https://github.com/Wenlab/Computation-Neuro-Course/assets/36225651/c3922bf2-d2c4-4b8e-bf07-6ede86bef597)
其中指数上的分子nT这项前面要加一个负号
这是我的证明
![IMG_20231010_145625](https://github.com/Wenlab/Computation-Neuro-Course/assets/36225651/2aca19c0-6ca4-432e-8a90-aaa9b59b3e07)

**Comment by Physics-Lee** [comment]
不，nT这项前面不需要加一个负号。

我更改了作业中的笔误，你再去看一下。

**Comment by HoutonBosta** [comment]
> 不，nT这项前面不需要加一个负号。
> 
> 我更改了作业中的笔误，你再去看一下。

我的证明到底哪里有问题啊？根据题目给的条件算出来和提示不一样。不是之前笔误的问题，这个这个证明我已经花了好几个小时反复推了很多遍了，都是这个结果

**Comment by Physics-Lee** [comment]
QQ群里已经回答了。多想想几何意义和物理意义，它俩直观，不要陷入代数和分析中。
