### ISSUE TITLE
为什么人们常说深度学习是一个黑盒子？

### ISSUE THREAD

**Issue by Physics-Lee** [Wenlab/Computation-Neuro-Course#58]
朋友，我不知道你是否有过这个疑惑。

在神经网络中，每个“突触”的权重都是知道的，权重的更新方法也是知道的（反向传播），如何从特征推断出标签也是知道的（前向传播）。

那么，为什么人们还把深度学习称为黑盒子呢？

（已经知道答案的同学可以揭晓答案，不知道的可以带着这个问题去学习本学期剩下的课程）

**Comment by HoutonBosta** [comment]
个人认为是即便你知道了每个权重和偏置量是怎么算出来的，但是你把这些数据拿出来分析，依然不知道这些权重和偏执量怎么就可以形成结果的，你只能理解输入和输出的数据，但是中间的那些参数是机器通过反向传播得到的结果，如果光给你中间层的数据，你很难根据这些数据理解它们在总体的任务处理中代表着什么计算逻辑和思路或者起到了什么结构上的作用。所以在某种程度上你只能理解输入和输出，就和黑盒子一样。
