### ISSUE TITLE
Do Jennifer Aniston cells mean bijection coding?

### ISSUE THREAD

**Issue by Physics-Lee** [Wenlab/Computation-Neuro-Course#60]
See this 3 minutes [video](https://www.youtube.com/watch?v=zDDyEql4TmQ), which introduce the concept of specificity coding (I like to call it bijection coding), population coding and sparse coding.

So, do Jennifer Aniston cells mean bijection coding?

This is an open question, say anything you want!

**Comment by YkLn0419** [comment]
既然助教老师提到了这个问题，那么我想借此机会来说一下我对人类记忆编码的一些不成熟的看法：
针对视频中提到的三种Sensory coding的方式——单一编码、集群编码和稀疏编码，这三种编码方式都是基于实验结果给出的合理的可能理论模型，但我个人认为，记忆的真实编码方式应该是量子化的，存在类似于“祖母细胞”这种的神经元，但这些神经元编码的应该不是具体的“祖母的一整张脸”，而是“祖母脸部的某些令人记忆深刻的特征”（这也是我认为为什么在祖母细胞的实验中，当看到除了JA的其他脸也会有部分细胞响应的原因）。
举个例子，以我们第一次见到温老师为例子，为了记住温老师的整个面容，我们需要选取他脸部几个明显的特征点进行记忆，可能部分同学记住的是温老师的胡子，部分同学记住的是温老师的眼镜，但我个人感觉很难记住温老师的一整张脸。合理推测，我们在记忆某个事物的过程中，记住的不是整体，而是这个整体中令人记忆深刻的某个或某些特征点，而这些特征点的Weight则和我们自身的注意力有关，还是以温老师为例子，我印象深刻的是温老师的胡子而非眼镜，因此这两个特征点在我脑中的Weight就不同（我看到胡子更容易想起是温老师而非眼镜）。
总结一下，我结合生活经验得到了一个我自己提出的模型：人脑中存在“祖母细胞”类似的神经元，用于双射编码特征点，当我们看到含有和记忆相似的特征点的图片时，这些”特征点细胞“被激活，产生集群响应，就像计算机一样从Pixel到整体，根据“特征点细胞”的响应进一步还原出整个人脸或是事件，因此我认为Sensory coding的方式可能是先双射编码，再集群编码。
我用我自己的模型尝试着解释了一些现象，例如Dejavu。既视感的产生可能正是因为我们当前所处的环境中有部分特征（例如阳光，位置，周围的人等等）与我们记忆中的特征点相似，导致了“特征点细胞”的响应，而进一步还原了记忆中的事件，因此我们会觉得这件事曾经发生过。
如果我有部分地方说的不对，还希望大家指正与批评，我个人对人脑的记忆编码非常感兴趣，这个模型是我从高中时期就开始构想了，近几年也在不断地学习中去完善它，希望有一天我能够真正意义上的让这个模型公之于众，谢谢大家！

**Comment by Physics-Lee** [comment]
挺不错的想法，可以想想怎么设计一个实验验证。Sent from my phone-------- Original message --------From: Kunlun_Yao ***@***.***>Date: Sun, Oct 22, 2023, 21:48To: Wenlab/Computation-Neuro-Course ***@***.***>Cc: Yixuan Li ***@***.***>, Author ***@***.***>Subject: Re: [Wenlab/Computation-Neuro-Course] Do Jennifer Aniston cells mean bijection coding? (Issue #60)
既然助教老师提到了这个问题，那么我想借此机会来说一下我对人类记忆编码的一些不成熟的看法：
针对视频中提到的三种Sensory coding的方式——单一编码、集群编码和稀疏编码，这三种编码方式都是基于实验结果给出的合理的可能理论模型，但我个人认为，记忆的真实编码方式应该是量子化的，存在类似于“祖母细胞”这种的神经元，但这些神经元编码的应该不是具体的“祖母的一整张脸”，而是“祖母脸部的某些令人记忆深刻的特征”（这也是我认为为什么在祖母细胞的实验中，当看到除了JA的其他脸也会有部分细胞响应的原因）。
举个例子，以我们第一次见到温老师为例子，为了记住温老师的整个面容，我们需要选取他脸部几个明显的特征点进行记忆，可能部分同学记住的是温老师的胡子，部分同学记住的是温老师的眼镜，但我个人感觉很难记住温老师的一整张脸。合理推测，我们在记忆某个事物的过程中，记住的不是整体，而是这个整体中令人记忆深刻的某个或某些特征点，而这些特征点的Weight则和我们自身的注意力有关，还是以温老师为例子，我印象深刻的是温老师的胡子而非眼镜，因此这两个特征点在我脑中的Weight就不同（我看到胡子更容易想起是温老师而非眼镜）。
总结一下，我结合生活经验得到了一个我自己提出的模型：人脑中存在“祖母细胞”类似的神经元，用于双射编码特征点，当我们看到含有和记忆相似的特征点的图片时，这些”特征点细胞“被激活，产生集群响应，就像计算机一样从Pixel到整体，根据“特征点细胞”的响应进一步还原出整个人脸或是事件，因此我认为Sensory coding的方式可能是先双射编码，再集群编码。
我用我自己的模型尝试着解释了一些现象，例如Dejavu。既视感的产生可能正是因为我们当前所处的环境中有部分特征（例如阳光，位置，周围的人等等）与我们记忆中的特征点相似，导致了“特征点细胞”的响应，而进一步还原了记忆中的事件，因此我们会觉得这件事曾经发生过。
如果我有部分地方说的不对，还希望大家指正与批评，我个人对人脑的记忆编码非常感兴趣，这个模型是我从高中时期就开始构想了，近几年也在不断地学习中去完善它，希望有一天我能够真正意义上的让这个模型公之于众，谢谢大家！

**Comment by YkLn0419** [comment]
> 挺不错的想法，可以想想怎么设计一个实验验证。Sent from my phone-------- Original message --------From: Kunlun_Yao ***@***.***>Date: Sun, Oct 22, 2023, 21:48To: Wenlab/Computation-Neuro-Course ***@***.***>Cc: Yixuan Li ***@***.***>, Author ***@***.***>Subject: Re: [Wenlab/Computation-Neuro-Course] Do Jennifer Aniston cells mean bijection coding? (Issue #60) 既然助教老师提到了这个问题，那么我想借此机会来说一下我对人类记忆编码的一些不成熟的看法： 针对视频中提到的三种Sensory coding的方式——单一编码、集群编码和稀疏编码，这三种编码方式都是基于实验结果给出的合理的可能理论模型，但我个人认为，记忆的真实编码方式应该是量子化的，存在类似于“祖母细胞”这种的神经元，但这些神经元编码的应该不是具体的“祖母的一整张脸”，而是“祖母脸部的某些令人记忆深刻的特征”（这也是我认为为什么在祖母细胞的实验中，当看到除了JA的其他脸也会有部分细胞响应的原因）。 举个例子，以我们第一次见到温老师为例子，为了记住温老师的整个面容，我们需要选取他脸部几个明显的特征点进行记忆，可能部分同学记住的是温老师的胡子，部分同学记住的是温老师的眼镜，但我个人感觉很难记住温老师的一整张脸。合理推测，我们在记忆某个事物的过程中，记住的不是整体，而是这个整体中令人记忆深刻的某个或某些特征点，而这些特征点的Weight则和我们自身的注意力有关，还是以温老师为例子，我印象深刻的是温老师的胡子而非眼镜，因此这两个特征点在我脑中的Weight就不同（我看到胡子更容易想起是温老师而非眼镜）。 总结一下，我结合生活经验得到了一个我自己提出的模型：人脑中存在“祖母细胞”类似的神经元，用于双射编码特征点，当我们看到含有和记忆相似的特征点的图片时，这些”特征点细胞“被激活，产生集群响应，就像计算机一样从Pixel到整体，根据“特征点细胞”的响应进一步还原出整个人脸或是事件，因此我认为Sensory coding的方式可能是先双射编码，再集群编码。 我用我自己的模型尝试着解释了一些现象，例如Dejavu。既视感的产生可能正是因为我们当前所处的环境中有部分特征（例如阳光，位置，周围的人等等）与我们记忆中的特征点相似，导致了“特征点细胞”的响应，而进一步还原了记忆中的事件，因此我们会觉得这件事曾经发生过。 如果我有部分地方说的不对，还希望大家指正与批评，我个人对人脑的记忆编码非常感兴趣，这个模型是我从高中时期就开始构想了，近几年也在不断地学习中去完善它，希望有一天我能够真正意义上的让这个模型公之于众，谢谢大家！ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

根据这个猜想，我设计了一个大致的实验。要想验证这个猜想，主要分为三点：
1.验证特征点记忆是否存在。以人作为实验对象（如果可以的话），观看一张生活中从未有印象的人脸，记录神经元集群响应R1。这张人脸上存在某些特征，例如眼镜、面部纹身、耳钉等等，给予受试者30s时间对面孔进行粗略记忆，30s后循环向受试者展示这些面部特征，与此同时记录人脑神经元活动（每个图像对应神经元集群响应强度为r1_i），若在播放不同特征图像时神经元响应区域不同，则代表这些不同的面部特征是由不同细胞进行记忆的。若确实由不同细胞进行记忆，不同特征图像对应的神经元响应强度可以粗略作为特征权重。
2.判断是否有进一步的集群编码。在第一点成立的基础上，将所有特征图像回归到人脸上，再次记录神经元集群响应，将r1_i视为刺激s，寻找s与R之间是否存在函数关系，多次实验进行建模验证。
3.依据第一次实验时得到的粗略估计权重对特征图象进行微调，当图像权重大时不进行调整，当权重小时进行微小调整（例如调整瞳色、发色等），对特征点进行调整之后重新放置到人脸上，再次向受试者展示人脸，记录神经元集群响应强度R2，同第一次实验循环播放特征点，记录神经元集群响应r2_i。
我们假设受试者将人脸B错误判断为人脸A的概率为P，则P可以通过根据第二点得到的函数，以及第三次实验中得到的数据r2_i推到出的可能的第二次全脸响应R2‘，与第二次看到时的响应强度R2的相似性进行估计，我们假设P是与R2，R2’有关的一个函数，则可以得到P=f(R2,R2‘)，其中R1=g(r1_i)，R2’=g(r2_i)，R2=h(r2_i)，当P大于某一值时，即可粗略证明第二点中得到的函数正确。（实际上就是理论值与实验值的比较）
我个人认为第二点中判断进一步集群编码的依据不是特别有力，希望助教老师能指导一下.

>

**Comment by Physics-Lee** [comment]
有点没看懂你的文字，咱们有空可以线下聊聊
