### ISSUE TITLE
数值求解微分方程组的初值问题

### ISSUE THREAD

**Issue by HoutonBosta** [Wenlab/Computation-Neuro-Course#63]
作业第二题H-H model求解电压时我发现想要求解电压，需要知道电压的初始值，也就是静息电位，然而要求解静息电位，就要令dV/dt为0，但是为了求解dV/dt=0，就必须引入n,m,h的初值，这些初值该怎么选取？还是说我们直接就认为静息电位是-70mV不考虑这么多？还是说可以先设置所有初值都为0，然后让其自行演化？

**Comment by HoutonBosta** [comment]
我通过自行演化的方法得到了静息时各个参数的值，问题已解决

**Comment by Physics-Lee** [comment]
我和你的做法是一样的
