### ISSUE TITLE
关于Ek、ENa、和EL取值的争议

### ISSUE THREAD

**Issue by HoutonBosta** [Wenlab/Computation-Neuro-Course#64]
当在网上查找HH model的相关数据时，会发现Ek、ENa和EL的数据存在差异，我在网上查找了一下资料有如下解释:
The parameters ENa, EK, and EL are the reversal potentials. Reversal potentials and conductances are empirical parameters. In Table [2.1]. These values are based on a voltage scale where the resting potential is zero. To get the values accepted today, the voltage scale has to be shifted by -65 mV. For example, the corrected value of the sodium reversal potential is ENa = 50 mV that of the potassium ions is EK = - 77 mV.
![image](https://github.com/Wenlab/Computation-Neuro-Course/assets/36225651/13118e3e-03df-46f3-843b-0037c61fefa2)

这个问题困扰了我很久，希望能够给大家带来帮助！
来源：https://lcnwww.epfl.ch/gerstner/SPNM/node14.html

**Comment by Physics-Lee** [comment]
这个资料里，   $E_{Na+}, E_{K+}, E_L$    的值都加上了65mV，目的是把-65mV的resting potential写成0mV，有点类似于高中选取重力势能零点。但在此处这么做没什么意义，因为 $V$,  $E_{Na+}, E_{K+}, E_L$ 是细胞膜内外的电势差，是一个不管你选哪里为电势零点都不变的量。

**Comment by Physics-Lee** [comment]
https://neuronaldynamics.epfl.ch/online/Ch2.S2.html

谷歌搜索下的第二个链接，里面给了参数的取值。参数都是实验上测出来的。
