### ISSUE TITLE
第二次作业附加题的提示

### ISSUE THREAD

**Issue by Physics-Lee** [Wenlab/Computation-Neuro-Course#65]
"Adaptation"，中文为适应，在神经科学里的意思也是此意。

比如，当你走进很香的食堂，刚开始会有很强烈的感觉，但过了几分钟就仿佛闻不到香喷喷的气味了。

人的视觉、听觉、嗅觉、味觉、触觉、痛觉均有明显的适应。

动物也有适应，甚至像秀丽隐杆线虫、海兔这样的低等动物也有。Eric Kandel获诺贝尔奖起源于他对海兔对机械刺激（机械刺激可以视为触觉，也可以视为痛觉）的适应的研究；线虫领域，有一位名叫Catherine Rankin的心理学家，把Kandel的做法搬到线虫上，成功证明了线虫有记忆（容易想到，能适应就代表有记忆），颠覆了当时的线虫圈。

神经元同样有适应。在电生理的数据上，学者们发现，给猴子看同样的刺激，**神经元的动作电位频率会越来越低，直到一个恒定值。**

于是乎，一些具有适应能力的模型被提出，附加题就是其中一个。

若你知道适应的意思，应该很容易能猜出此题的答案。

再提示几个坑：

* 用Euler Method去求微分方程的数值解，不要在每个小段上画解析解再把它们拼起来。
* 用Euler Method时，狄拉克函数直接变成了0或者1。
* 本题中所给的一阶微分方程有很明显的几何意义和物理意义，不要掉进代数和分析里。

---

PS: 我也不是做题机器，做此题前前后后也花了四五个小时，一时半会没做出来要保持冷静、仔细思考。

**Comment by peterlv2003** [comment]
请问我在（b）小题中解析求出函数，再代入数据近似求出频率可以吗？

**Comment by Physics-Lee** [comment]
完全可以这样做，但这么做只能求出 $f$ 和 $T$，无法求出 $V(t)$ 和 $I_{adapt}(t)$。

这道题的目的之一是让大家熟悉Euler Method，它很实用，且并不难。

附加题若拿满分需要求出 $V(t)$。

**Comment by peterlv2003** [comment]
就是在（c）小题只要用欧拉法就可以了对吧？

**Comment by peterlv2003** [comment]
毕竟老师的代码就是欧拉法。但是（b）小题求不出解析解吗？我用提示的周期条件得到了V和Ia的解析啊？

**Comment by Physics-Lee** [comment]
> 就是在（c）小题只要用欧拉法就可以了对吧？

是的

> 但是（b）小题求不出解析解吗？我用提示的周期条件得到了V和Ia的解析啊？

可以求出解析解，但是，这是稳态时候的解析解，而用欧拉法可以得到瞬态和稳态的数值解。

**Comment by peterlv2003** [comment]
那么瞬态和稳态都要求吗？

**Comment by Physics-Lee** [comment]
解析解上，你几乎不可能求出瞬态的解析解。

数值解上，都要求。

**Comment by peterlv2003** [comment]
明白了，谢谢！
