### ISSUE TITLE
我们到底还能不能理解生物神经网络或人工神经网络？

### ISSUE THREAD

**Issue by Physics-Lee** [Wenlab/Computation-Neuro-Course#66]
我常常在思考一件事：

有人说，我们想理解一个足够复杂的系统，是不可能的，比如，我们永远不可能理解像人脑、Transformer这样复杂的系统，永远不能把这俩黑盒子变成白盒子，只能理解输入和输出。**如果这种说法是真的，那么我们永远都不能理解生物神经网络和人工神经网络了。**

吴思老师在最近的[采访](https://mp.weixin.qq.com/s/yUrrIEPb5wMrFwN-UhPHVQ)中就流露了这样的观点。

但是吧，秀丽线虫，只有302个神经元，却能完成感觉、运动、学习、记忆等行为。302个神经元算是很复杂的系统吗？

那么，有两种可能的情况

* 低等生物和高等生物的生物神经网络有本质的不同，我们能理解秀丽线虫的生物神经网络，但是不能理解人的生物神经网络。
* 低等生物和高等生物的生物神经网络没有本质的不同，我们既能理解秀丽线虫的生物神经网络，也能理解人的生物神经网络。

你更看好那种情况呢？

**Comment by HoutonBosta** [comment]
我觉得首先要对“理解”一词做一个解释，我们通常情况下理解一个事物是指我们可以用一些已知的事实(公理)和简单的逻辑来分步拆分一个复杂的问题，当这个问题被逐一分解成若干简单的“问题单元”时，我们可以分别理解每个“问题单元”，然后再把这些“问题单元”拼凑起来，然而想要理解复杂的大脑似乎很难这样做，如果我们采用研究物质学科的那种“分而治之”的研究方法也许我们可以搞清楚单个脑区或者说单个神经元是如何运转的，但是有的问题是没法采用这种“分而治之”的方法，比如脑区之间复杂的相互作用，必须总体的进行考量，但是如果我们想要对其进行总体的考量，就意味着我们要“同时”理解大量的“问题单元”（或者说联系“问题单元”得出的答案），这种“同时”理解大量的问题对于弱小的人类而言是困难的，但是如果你不尝试“同时”去理解那就又回到了分析单个神经元和单个脑区的情形，因为脑区之间的复杂相互作用难以笼统地定性分析，但是你试图定量的时候又发现太过复杂。就好比不允许你打草稿还要你一眼瞪出两个三位数乘积的答案一样(当然理解大脑可比这个问题难得多)，当然人工神经网络也是如此，我们仅仅只是笼统地知道每个参数是如何通过反向传播算出来的，但是我们难以一眼盯出这些参数对数据产生了什么复杂的影响。
所以我的观点是：低等生物和高等生物的生物神经网络没有本质的不同，但是随着网络的复杂度增加，我们试图采用的“分而治之”的理解手段逐渐失效了。我们也许可以理解人的生物神经网络，不过我们可能需要换一种科学观、方法论和思维模式。当然，我们还可以试图让聪明的人工智能来帮我们理解大脑，我相信等到技术发展到一定程度，人工智能的“瞪眼”能力应该比人类强。所以未来人类是否可以完全理解大脑我是持一种乐观的态度的。

**Comment by Physics-Lee** [comment]
不错
