### ISSUE TITLE
关于HW3第一题的问题

### ISSUE THREAD

**Issue by peterlv2003** [Wenlab/Computation-Neuro-Course#68]
请问c小题“Use a Poisson generator with the computed rate”是什么意思？“computed rate”指什么？
下文中“this linear estimate”指的是b小题的结果吗？
请问是要用泊松分布生成一组stimulate输入到b小题的模型中然后生成r吗？

**Comment by Pripribiologist** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我是李品洁，已收到您发来的邮件，我会尽快处理，祝好~

**Comment by Physics-Lee** [comment]
(c)的意思是用实验数据的firing rate作为泊松过程的 $\lambda$ , 去生成完美的泊松过程。

**Comment by peterlv2003** [comment]
原来如此，谢谢！

**Comment by peterlv2003** [comment]
> (c)的意思是用实验数据的firing rate作为泊松过程的 
> λ
>  , 去生成完美的泊松过程。

请问生成的一定要是原数据那样的0或1吗？还有请问如果生成的firing rate有负值怎么办？

**Comment by Physics-Lee** [comment]
> 请问生成的一定要是原数据那样的0或1吗？

这样最方便。

> 还有请问如果生成的firing rate有负值怎么办？

$r := \frac{\Delta n}{\Delta t} $，怎么可能是负的。

PS: 你问GPT，”请帮我写一个用MATLAB模拟泊松过程的函数“，就可以了。

**Comment by peterlv2003** [comment]
> r:=ΔnΔt，怎么可能是负的。

这个r不是第二问中用kernal估计的r_est吗？如果说就是原数据算的，那么dt应该取多少？

**Comment by peterlv2003** [comment]
哦，是用总的平均值来生成一个序列，这个序列满足泊松分布，没错吧？

**Comment by Physics-Lee** [comment]
> 这个r不是第二问中用kernal估计的r_est吗？如果说就是原数据算的，那么dt应该取多少？

估计的r_est当然可以有负的，这说明这个模型不对呗。一种改进模型的方法是假如激活函数。我在QQ群里已经给过这个提示了。

**Comment by Physics-Lee** [comment]
> 哦，是用总的平均值来生成一个序列，这个序列满足泊松分布，没错吧？

是的

**Comment by Physics-Lee** [comment]
你可能需要再仔细读一读温老师的note

**Comment by peterlv2003** [comment]
> 是的

好的，谢谢！

**Comment by peterlv2003** [comment]
> 你可能需要再仔细读一读温老师的note

这里的内容基本忘光了，我是对照笔记，习题课内容和老师的讲义写的;)

**Comment by Pripribiologist** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我是李品洁，已收到您发来的邮件，我会尽快处理，祝好~
