### ISSUE TITLE
Time Sery Is All You Need

### ISSUE THREAD

**Issue by Physics-Lee** [Wenlab/Computation-Neuro-Course#70]
Hey, I am going to tell you a funny thing: Time Sery Is All You Need (to reconstruct the topology)

Remember in HH model, we do some simulations, using 4 non-linear ODEs to get 4 time series $V(t), n(t), m(t), h(t)$?

Now, follow my instructions:
* First, only pick $V(t)$, drop all other time series.
* Second, choose 2 super-parameters $\tau$ and $n$
* Third, save $V(t), V(t-\tau), V(t-2\tau) ... V(t-n\tau)$.

Then, we will get an amazing result: when you plot $V(t), V(t-\tau), V(t-2\tau) ... V(t-n\tau)$ in $n+1$ dimension and then use dimension-reduction technique like PCA to 4D, you can get the same topology as the original ODEs!

For example, below figure is for the case of Lorenz ODES.

![image](https://github.com/Wenlab/Computation-Neuro-Course/assets/68525696/3ed60cf6-e25c-4862-84b9-b328cd88bcea)

**Comment by Physics-Lee** [comment]
![1](https://github.com/Wenlab/Computation-Neuro-Course/assets/68525696/b671c9b3-a00a-499e-87ec-56813d8009a8)
![2](https://github.com/Wenlab/Computation-Neuro-Course/assets/68525696/ba4e0188-9e15-4f90-9f95-4be8ccdadbec)

My own simulation!

Just use GPT~

**Comment by Pripribiologist** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我是李品洁，已收到您发来的邮件，我会尽快处理，祝好~
