### ISSUE TITLE
HW4模拟Hopfield第二问随着P增加error率反而下降？

### ISSUE THREAD

**Issue by ZhangLixian1023** [Wenlab/Computation-Neuro-Course#71]
![result0-1200](https://github.com/Wenlab/Computation-Neuro-Course/assets/80459388/dcd89146-1cad-4176-8a10-bf852844761e)
这是第四次作业第二题，题目说让模拟P=10-100的情况，这时候随着P增加，error率上升。随后，我扩大到0-1200，发现如上图所示，P达到300之后error就开始下降。怎么理解这个现象？（是我程序写错了吗？好反直觉）

**Comment by ZhangLixian1023** [comment]
可能的原因是：随着P的增加，程序中随机生成的P个记忆模式的线性相关性更大了（彼此不再正交）。如果在写程序的时候，保证生成的P个记忆模式两两正交（即 cos = 0 )，估计能够使得 error 随着 P 的增加总是增加。当然，为了保证正交性，P必须小于N。我试试之后再来这里。

**Comment by Physics-Lee** [comment]
看上去很有意思的模拟结果，我来试一试。

**Comment by Physics-Lee** [comment]
你的纵轴的错误率是pattern出错的概率还是neuron出错的概率？

我自己模拟了一下，在两种情况下，都没有发现你说的现象。

![Uploading Screenshot 2024-01-29 202248.png…]()
