### ISSUE TITLE
大研

### ISSUE THREAD

**Issue by Physics-Lee** [Wenlab/Computation-Neuro-Course#72]
对此项目感兴趣的同学可以邮件联系温老师。

![QQ图片20240222153506](https://github.com/Wenlab/Computation-Neuro-Course/assets/68525696/4b1ce2a1-cbb0-479d-b20a-127692b99825)

**Comment by Pripribiologist** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我是李品洁，已收到您发来的邮件，我会尽快处理，祝好~
